"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Expense={id:string;title:string;vendor:string|null;amountCents:number;dueDate:string;status:string;categoryId:string|null;category:string|null;icon:string|null;payerId:string;payer:string;notes:string|null};
type Category={id:string;name:string;icon:string|null;color:string|null}; type Member={id:string;name:string;email:string;role:string};
type Dashboard={user:{id:string;name:string;email:string};household:{id:string;name:string;role:string};settings:{monthlyIncomeCents:number;monthlyBudgetCents:number;reminderDays:string};categories:Category[];members:Member[];expenses:Expense[];summary:{incomeCents:number;budgetCents:number;spentCents:number;openCents:number;availableCents:number}};
const money=(cents:number)=>new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF"}).format(cents/100);
const date=(value:string)=>new Intl.DateTimeFormat("de-CH",{day:"numeric",month:"short"}).format(new Date(`${value}T12:00:00`));
const statusLabel:Record<string,string>={OPEN:"Offen",PAID:"Bezahlt",OVERDUE:"Überfällig",CANCELLED:"Storniert"};

export default function Home(){
 const[data,setData]=useState<Dashboard|null>(null);const[error,setError]=useState("");const[query,setQuery]=useState("");const[filter,setFilter]=useState("Alle");const[modal,setModal]=useState<"expense"|"settings"|"member"|null>(null);const[saving,setSaving]=useState(false);const[toast,setToast]=useState("");
 const load=useCallback(async()=>{try{setError("");const response=await fetch("/api/dashboard",{cache:"no-store"});if(!response.ok)throw new Error();setData(await response.json());}catch{setError("Deine Haushaltsdaten konnten nicht geladen werden.");}},[]);
 // Data arrives asynchronously from the authenticated household API.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>data?.expenses.filter(x=>(filter==="Alle"||statusLabel[x.status]===filter)&&`${x.title} ${x.vendor||""}`.toLowerCase().includes(query.toLowerCase()))??[],[data,filter,query]);
 const categoryTotals=useMemo(()=>{const map=new Map<string,number>();data?.expenses.filter(x=>x.status!=="CANCELLED").forEach(x=>map.set(x.category||"Sonstiges",(map.get(x.category||"Sonstiges")||0)+x.amountCents));return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4)},[data]);
 function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),2600)}
 async function mutate(url:string,options:RequestInit,message:string){setSaving(true);try{const response=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Aktion fehlgeschlagen.")}setModal(null);await load();notify(message)}catch(e){notify(e instanceof Error?e.message:"Aktion fehlgeschlagen.")}finally{setSaving(false)}}
 async function changeStatus(id:string,status:string){await mutate("/api/expenses",{method:"PATCH",body:JSON.stringify({id,status})},status==="PAID"?"Rechnung als bezahlt markiert.":"Status aktualisiert.")}
 async function remove(id:string){if(confirm("Diese Rechnung wirklich löschen?"))await mutate(`/api/expenses?id=${id}`,{method:"DELETE"},"Rechnung gelöscht.")}
 if(!data)return <main className="loading"><div className="brand"><span className="brandmark">H</span><span>Haus<span>Halt</span></span></div><div className="loader"/><p>{error||"Dein Haushalt wird vorbereitet …"}</p>{error&&<button className="primary" onClick={load}>Noch einmal versuchen</button>}</main>;
 const monthName=new Intl.DateTimeFormat("de-CH",{month:"long",year:"numeric"}).format(new Date());const ratio=data.summary.incomeCents?Math.max(0,Math.round(data.summary.availableCents/data.summary.incomeCents*100)):0;
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><span className="brandmark">H</span><span>Haus<span>Halt</span></span></div><div className="house-switch"><div><small>AKTUELLER HAUSHALT</small><strong>{data.household.name}</strong></div><span>⌄</span></div><nav><a className="active" href="#dashboard"><span>▦</span>Übersicht</a><a href="#rechnungen"><span>▤</span>Rechnungen <b>{data.expenses.filter(x=>x.status==="OPEN"||x.status==="OVERDUE").length}</b></a><a href="#budget"><span>◒</span>Budget</a><a href="#aufteilung"><span>⇄</span>Aufteilung</a><button onClick={()=>setModal("member")}><span>♙</span>Mitglieder</button><p>VERWALTUNG</p><a href="#kategorien"><span>◇</span>Kategorien</a><button onClick={()=>setModal("settings")}><span>⚙</span>Einstellungen</button></nav><div className="profile"><div className="avatar">{data.user.name.slice(0,2).toUpperCase()}</div><div><strong>{data.user.name}</strong><small>{data.household.role}</small></div><button aria-label="Profilmenü">•••</button></div></aside>
  <section className="content" id="dashboard"><header><div><p>{new Intl.DateTimeFormat("de-CH",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date())}</p><h1>Guten Tag, {data.user.name.split(" ")[0]}</h1></div><div className="header-actions"><button className="icon-btn" aria-label="Benachrichtigungen">♢{data.expenses.some(x=>x.status==="OVERDUE")&&<i/>}</button><button className="primary" onClick={()=>setModal("expense")}><span>＋</span> Rechnung erfassen</button></div></header>
   <section className="summary"><article><div className="metric-icon green">↙</div><div><small>EINNAHMEN</small><strong>{money(data.summary.incomeCents)}</strong><p onClick={()=>setModal("settings")}>Monatsbetrag bearbeiten</p></div></article><article><div className="metric-icon coral">↗</div><div><small>AUSGABEN</small><strong>{money(data.summary.spentCents)}</strong><p>{monthName}</p></div></article><article><div className="metric-icon blue">◷</div><div><small>OFFENE RECHNUNGEN</small><strong>{money(data.summary.openCents)}</strong><p>{data.expenses.filter(x=>x.status==="OPEN"||x.status==="OVERDUE").length} Rechnungen ausstehend</p></div></article><article className="balance"><div><small>VERFÜGBAR</small><strong>{money(data.summary.availableCents)}</strong><p>{ratio}% deines Einkommens</p></div><div className="ring" style={{background:`conic-gradient(var(--mint) ${ratio}%,#315652 0)`}}><span>{ratio}%</span></div></article></section>
   <section className="grid-main"><article className="panel spending" id="budget"><div className="panel-head"><div><h2>Budget im Überblick</h2><p>{monthName}</p></div><button onClick={()=>setModal("settings")}>Bearbeiten</button></div><div className="budget-progress"><div><span style={{width:`${Math.min(100,data.summary.budgetCents?data.summary.spentCents/data.summary.budgetCents*100:0)}%`}}/></div><strong>{money(data.summary.spentCents)} <small>von {money(data.summary.budgetCents)}</small></strong><p>{data.summary.budgetCents?Math.max(0,Math.round((data.summary.budgetCents-data.summary.spentCents)/100)):0} CHF Budget verbleibend</p></div></article><article className="panel categories" id="kategorien"><div className="panel-head"><div><h2>Nach Kategorien</h2><p>{monthName}</p></div></div><div className="donut"><div><strong>{money(data.summary.spentCents)}</strong><small>Total</small></div></div><ul>{categoryTotals.length?categoryTotals.map(([name,total],i)=><li key={name}><span><i className={`dot c${i}`}/>{name}</span><b>{data.summary.spentCents?Math.round(total/data.summary.spentCents*100):0}%</b></li>):<li>Noch keine Ausgaben</li>}</ul></article></section>
   <section className="panel bills" id="rechnungen"><div className="panel-head"><div><h2>Rechnungen</h2><p>Fälligkeiten erfassen, aufteilen und begleichen</p></div><button className="add-small" onClick={()=>setModal("expense")}>＋ Neue Rechnung</button></div><div className="toolbar"><input aria-label="Rechnungen durchsuchen" placeholder="Rechnung suchen …" value={query} onChange={e=>setQuery(e.target.value)}/><div>{["Alle","Offen","Überfällig","Bezahlt"].map(x=><button key={x} className={filter===x?"selected":""} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="table-wrap">{filtered.length?<table><thead><tr><th>RECHNUNG</th><th>FÄLLIG</th><th>ZUSTÄNDIG</th><th>BETRAG</th><th>STATUS</th><th>AKTIONEN</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><span className="bill-icon">{b.icon||"◇"}</span><div><strong>{b.title}</strong><small>{b.category||"Sonstiges"}{b.vendor?` · ${b.vendor}`:""}</small></div></td><td>{date(b.dueDate)}</td><td><span className="mini-avatar">{b.payer.slice(0,1)}</span>{b.payer}</td><td><strong>{money(b.amountCents)}</strong></td><td><span className={`status ${b.status.toLowerCase()}`}>{statusLabel[b.status]}</span></td><td><div className="row-actions">{b.status!=="PAID"&&<button title="Als bezahlt markieren" onClick={()=>changeStatus(b.id,"PAID")}>✓</button>}<button title="Löschen" onClick={()=>remove(b.id)}>×</button></div></td></tr>)}</tbody></table>:<div className="empty"><span>▤</span><h3>Keine Rechnungen gefunden</h3><p>Erfasse deine erste Rechnung oder ändere den Filter.</p><button className="primary" onClick={()=>setModal("expense")}>Rechnung erfassen</button></div>}</div></section>
   <section className="split-card" id="aufteilung"><div><span className="split-icon">⇄</span><div><h2>Faire Aufteilung inklusive</h2><p>Jede neue Rechnung wird centgenau auf die ausgewählten Haushaltsmitglieder verteilt.</p></div></div><button onClick={()=>setModal("member")}>{data.members.length} Mitglieder verwalten →</button></section>
  </section>
  {modal==="expense"&&<ExpenseModal data={data} saving={saving} close={()=>setModal(null)} submit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate("/api/expenses",{method:"POST",body:JSON.stringify({title:f.get("title"),vendor:f.get("vendor")||undefined,amountCents:Math.round(Number(f.get("amount"))*100),dueDate:f.get("dueDate"),categoryId:f.get("categoryId"),payerId:f.get("payerId"),memberIds:data.members.filter(m=>f.get(`member-${m.id}`)).map(m=>m.id),recurrence:f.get("recurrence"),notes:f.get("notes")||undefined})},"Rechnung gespeichert.")}}/>}
  {modal==="settings"&&<SettingsModal data={data} saving={saving} close={()=>setModal(null)} submit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate("/api/dashboard",{method:"PATCH",body:JSON.stringify({incomeCents:Math.round(Number(f.get("income"))*100),budgetCents:Math.round(Number(f.get("budget"))*100)})},"Budget aktualisiert.")}}/>}
  {modal==="member"&&<MemberModal data={data} saving={saving} close={()=>setModal(null)} submit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await mutate("/api/members",{method:"POST",body:JSON.stringify({name:f.get("name"),email:f.get("email")})},"Mitglied hinzugefügt.")}}/>}
  {toast&&<div className="toast"><span>✓</span><div><strong>{toast}</strong></div></div>}
 </main>
}

function ModalShell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><div><small>HAUSHALT</small><h2>{title}</h2></div><button type="button" onClick={close} aria-label="Schließen">×</button></header>{children}</section></div>}
function ExpenseModal({data,saving,close,submit}:{data:Dashboard;saving:boolean;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <ModalShell title="Neue Rechnung" close={close}><form onSubmit={submit}><div className="form-grid"><label className="wide">Bezeichnung<input name="title" required minLength={2} placeholder="z. B. Miete September" autoFocus/></label><label>Anbieter<input name="vendor" placeholder="z. B. Verwaltung"/></label><label>Betrag in CHF<input name="amount" type="number" min="0.05" step="0.05" required placeholder="0.00"/></label><label>Fällig am<input name="dueDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Kategorie<select name="categoryId" required>{data.categories.map(x=><option key={x.id} value={x.id}>{x.icon} {x.name}</option>)}</select></label><label>Bezahlt von<select name="payerId">{data.members.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Wiederholung<select name="recurrence"><option value="NONE">Einmalig</option><option value="MONTHLY">Monatlich</option><option value="QUARTERLY">Quartalsweise</option><option value="YEARLY">Jährlich</option></select></label><fieldset className="wide"><legend>Kosten aufteilen</legend>{data.members.map(x=><label className="check" key={x.id}><input type="checkbox" name={`member-${x.id}`} defaultChecked/> {x.name}</label>)}</fieldset><label className="wide">Notiz<textarea name="notes" maxLength={1000} placeholder="Optional"/></label></div><div className="modal-actions"><button type="button" onClick={close}>Abbrechen</button><button className="primary" disabled={saving}>{saving?"Speichern …":"Rechnung speichern"}</button></div></form></ModalShell>}
function SettingsModal({data,saving,close,submit}:{data:Dashboard;saving:boolean;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <ModalShell title="Monatsbudget" close={close}><form onSubmit={submit}><div className="form-grid"><label>Nettoeinkommen CHF<input name="income" type="number" min="0" step="0.05" defaultValue={data.settings.monthlyIncomeCents/100}/></label><label>Ausgabenbudget CHF<input name="budget" type="number" min="0" step="0.05" defaultValue={data.settings.monthlyBudgetCents/100}/></label></div><p className="form-help">Diese Werte gelten für die aktuelle Monatsübersicht.</p><div className="modal-actions"><button type="button" onClick={close}>Abbrechen</button><button className="primary" disabled={saving}>Speichern</button></div></form></ModalShell>}
function MemberModal({data,saving,close,submit}:{data:Dashboard;saving:boolean;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <ModalShell title="Haushaltsmitglieder" close={close}><div className="member-list">{data.members.map(x=><div key={x.id}><span className="avatar">{x.name.slice(0,2).toUpperCase()}</span><div><strong>{x.name}</strong><small>{x.email} · {x.role}</small></div></div>)}</div><form onSubmit={submit}><h3>Mitglied hinzufügen</h3><div className="form-grid"><label>Name<input name="name" required minLength={2}/></label><label>E-Mail<input name="email" type="email" required/></label></div><p className="form-help">Das Mitglied wird dem Haushalt hinzugefügt. Einladungs-E-Mails folgen in der SaaS-Ausbaustufe.</p><div className="modal-actions"><button type="button" onClick={close}>Schließen</button><button className="primary" disabled={saving}>Hinzufügen</button></div></form></ModalShell>}
